### ISSUE TITLE
Test Failure outside test suite

### ISSUE THREAD

**Issue by bhedana** [BurnerDev/boilerplate-client#8]
1) application Uncaught error outside test suite:
     Uncaught Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
      at Error (native)
      at Sign.sign (crypto.js:279:26)
      at Object.sign (node_modules/firebase/node_modules/jsonwebtoken/node_modules/jws/node_modules/jwa/index.js:54:45)
      at Object.jwsSign [as sign] (node_modules/firebase/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:23:24)
      at Object.JWT.sign (node_modules/firebase/node_modules/jsonwebtoken/index.js:137:16)
      at authJwt (node_modules/firebase/auth-node/auth.js:83:16)
      at fetchAccessToken (node_modules/firebase/auth-node/auth.js:96:17)
      at [object Object].INTERNAL.getToken (node_modules/firebase/auth-node/auth.js:196:14)
      at Zb.getToken (node_modules/firebase/database-node.js:28:3496)
      at yh (node_modules/firebase/database-node.js:195:334)
      at [object Object]._onTimeout (node_modules/firebase/database-node.js:191:256)

this appears to be failing communication with firebase.. 
likely related to service account authentication

**Comment by bhedana** [comment]
this appears to have been resolved after updating firebase npm to latest
